apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: web-prod

# Em prod usamos 3 réplicas
replicas:
  - name: web
    count: 3

configMapGenerator:
  - name: web-pagina
    behavior: replace
    files:
      - index.html
